import type { Metadata, Viewport } from "next";
import { Heebo } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { SerwistProvider } from "./serwist-provider";
import "driver.js/dist/driver.css";
import "./globals.css";

const heebo = Heebo({
  subsets: ["hebrew", "latin"],
  variable: "--font-heebo",
});

export const metadata: Metadata = {
  title: "טירונט",
  description: "מערכת ניהול אימוני טירונות",
  manifest: "/manifest.json",
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/favicon-32.png", sizes: "32x32", type: "image/png" },
    ],
    // apple-touch-icon — used by iOS for the home screen icon.
    // appleWebApp alone does not emit this link tag.
    apple: "/icons/icon-192.png",
    other: [
      { rel: "mask-icon", url: "/mask-icon.svg", color: "#273617" },
    ],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "טירונט",
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#273617" },
    { media: "(prefers-color-scheme: dark)", color: "#1a1a1a" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html lang="he" dir="rtl" suppressHydrationWarning style={{ backgroundColor: "#fff" }}>
      <head>
        {/* Next.js 16 emits "mobile-web-app-capable" but NOT the Apple-prefixed
            version. iOS Safari requires the Apple prefix to enable PWA splash
            screens and standalone mode features. */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/* Inline theme init — runs before paint to set .dark class and avoid flash.
            Reads the user's stored preference from localStorage. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{performance.mark("theme-init");var p=localStorage.getItem("tironet:theme")||"system";var d=p==="dark"||(p==="system"&&matchMedia("(prefers-color-scheme:dark)").matches);if(d){document.documentElement.classList.add("dark");document.documentElement.style.backgroundColor="#1a1a1a"}sessionStorage.setItem("tironet:boot",JSON.stringify({t:Date.now(),theme:p,dark:d,w:screen.width,h:screen.height,dpr:devicePixelRatio}))}catch(e){}})()`,
          }}
        />
        {/* iOS PWA splash screens — generated by scripts/generate-splash.mjs
            Uses brand green bg (#273617) without prefers-color-scheme so iOS
            reliably matches the media query on all versions. */}
        {/* iPhones */}
        <link rel="apple-touch-startup-image" href="/splash/iphone-se-1.png" media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-8.png" media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-8-plus.png" media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-x.png" media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-xr.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-xs-max.png" media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-12-mini.png" media="(device-width: 360px) and (device-height: 780px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-12.png" media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-14-plus.png" media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-15-pro.png" media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-15-pro-max.png" media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-16-pro.png" media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/iphone-16-pro-max.png" media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)" />
        {/* iPads */}
        <link rel="apple-touch-startup-image" href="/splash/ipad-mini.png" media="(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/ipad-9.png" media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/ipad-10.png" media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/ipad-air.png" media="(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/ipad-pro-11.png" media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
        <link rel="apple-touch-startup-image" href="/splash/ipad-pro-12.png" media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)" />
      </head>
      <body className={`${heebo.variable} font-sans antialiased`}>
        {/* Inline splash shown instantly before React/CSS load. Hidden once
            the first child paints. Uses inline styles so it works even when
            stylesheets haven't loaded yet. Colors adapt to dark mode via the
            .dark class set by the inline script above. */}
        <div
          id="app-splash"
          style={{
            position: "fixed",
            inset: 0,
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            zIndex: 9999,
          }}
        />
        <style
          dangerouslySetInnerHTML={{
            __html: `#app-splash{background:#fff}.dark #app-splash{background:#1a1a1a}#app-splash::after{content:"";width:36px;height:36px;border:3px solid #e5e7eb;border-top-color:#273617;border-radius:50%;animation:app-splash-spin .7s linear infinite}.dark #app-splash::after{border-color:#333;border-top-color:#7C9A6D}@keyframes app-splash-spin{to{transform:rotate(360deg)}}`,
          }}
        />
        <SerwistProvider>
          <NextIntlClientProvider messages={messages}>
            <ThemeProvider>
              {children}
              <Toaster />
            </ThemeProvider>
          </NextIntlClientProvider>
        </SerwistProvider>
      </body>
    </html>
  );
}
